### ISSUE TITLE
Composor install issue

### ISSUE THREAD

**Issue by frits-ffp** [uazgraduatecollege/cakephp-casauth#3]
first of all, thanks for this project.
unfortunately when installing via composer I get the following message when i use 
`php composer.phar update`

`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires uazgraduatecollege/cakephp-casauth, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`

in my 'composer.json' file i have the following

"require": {
        "php": ">=7.2",
        "cakephp/cakephp": "^4.3",
        "cakephp/migrations": "^3.2",
        "cakephp/plugin-installer": "^1.3",
        "mobiledetect/mobiledetectlib": "^2.8",
        "uazgraduatecollege/cakephp-casauth": "^1.0"
        
    },"

any ideas?

**Comment by pbarabe** [comment]
@frits-ffp Thanks for reaching out. You'll need to identify the repository's source using composer's `repositories` property in your composer.json (see below). I'm updating the README to reflect this.

```json
    "repositories": [
      {
        "type": "git",
        "url": "https://github.com/uazgraduatecollege/cakephp-casauth.git"
      }
    ],
    "require": {
        "uazgraduatecollege/cakephp-casauth": "~1.0"
    }
}
```

**Comment by pbarabe** [comment]
@frits-ffp I went ahead and registered this package on packagist.org, so adding the `repositories` property _shouldn't_ be necessary.

**Comment by frits-ffp** [comment]
Thank you very much, it installed flawless now.
